FROM oven/bun:alpine
WORKDIR /app

RUN bun install -g pm2
RUN apk add --no-cache curl
EXPOSE 3000 3001

COPY deploy.tar.gz ./deploy.tar.gz

RUN tar -xzf deploy.tar.gz -C /app

CMD ["pm2-runtime", "start", "ecosystem.json"]
