name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  check:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint

      - name: Test
        run: bun run test

      - name: Build
        run: bun run build
  changepacks:
    name: changepacks
    runs-on: ubuntu-latest
    permissions:
      # create pull request comments
      pull-requests: write

      # Actions > General > Workflow permissions for creating pull request
      # Create brench to create pull request
      contents: write
    needs:
      - check
    steps:
      - uses: actions/checkout@v5
      - uses: changepacks/action@main
        id: changepacks
    outputs:
      changepacks: ${{ steps.changepacks.outputs.changepacks }}
  deploy:
    name: deploy
    needs: changepacks
    if: contains(needs.changepacks.outputs.changepacks, 'package.json') || github.ref == 'refs/heads/dev'
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: compress
        run: |
          cp pyproject.toml ./apis/pyproject.toml
          cp uv.lock ./apis/uv.lock

          cp package.json ./apps/package.json
          cp bun.lock ./apps/bun.lock
          cp ecosystem.json ./apps/ecosystem.json
          zip -r deploy.zip . -x '.git' -x '.github' -x 'infra/*' -x '.*/*'

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: deploy
          path: deploy.tar.gz
      - name: scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: deploy.tar.gz
          target: ~/deploy.tar.gz

      - name: ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/
            docker compose down
            find . -mindepth 1 -maxdepth 1 ! -name 'deploy.tar.gz' -exec rm -rf {} +
            tar -zxf deploy.tar.gz
            rm -rf deploy.tar.gz
            docker compose -f docker-compose.yml up -d --build

