name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  check:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: oven-sh/setup-bun@v2

      - name: bun install
        run: bun install

      - name: bun run lint
        run: bun -F ./apps/front -F ./apps/admin lint

      - name: bun run build
        run: bun -F ./apps/front -F ./apps/admin build

      - name: compress
        if: github.ref == 'refs/heads/main'
        run: |
          if [ -f .gitignore ]; then
            EXCLUDES=$(grep -v '^#' .gitignore | grep -v '^$' | grep -vE '^(\.next|out)/?$' | sed 's|^|--exclude=|')
            tar $EXCLUDES --exclude='.git' --exclude='.github' -zcf deploy.tar.gz .
          else
            tar --exclude='.git' --exclude='.github' -zcf deploy.tar.gz .
          fi

      - name: upload
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: deploy
          path: deploy.tar.gz
      - name: scp
        if: github.ref == 'refs/heads/main'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: deploy.tar.gz
          target: ~/deploy.tar.gz

      - name: ssh
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/
            tar -zxf deploy.tar.gz
            rm -rf deploy.tar.gz
            docker compose -f docker-compose.yml up -d
